---

- name: Install Latest Tomcat
  yum: name=tomcat state=present

- name: configuration file
  template:
    src: "tomcat7-server.xml.j2"
    dest: "/etc/tomcat/server.xml"
    owner: tomcat
    group: tomcat
    mode: 0644
  notify:
    - restart tomcat

- name: users configuration file
  template:
    src: "tomcat-users.xml.j2"
    dest: "/etc/tomcat/tomcat-users.xml"
    owner: tomcat
    group: tomcat
    mode: 0644
  notify:
    - restart tomcat

- name: insert firewalld rule for tomcat http port
  firewalld: port={{ tomcat_port }}/tcp permanent=true state=enabled immediate=yes