- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install basic apt packages (if any are configured).
  apt: "name={{basic_packages | list}} state=present"  
  when: basic_packages | length

- name: Install extra apt packages (if any are configured).
  apt: "name={{extra_packages | list}} state=present"  
  when: extra_packages | length