__php_packages:
  - php7.0
  - php7.0-mcrypt
  - php7.0-cli
  - php7.0-curl
  - php7.0-gd
  - php-pear

__php_webserver_daemon: "apache2"

# Vendor-specific configuration paths on Debian/Ubuntu make my brain asplode.
__php_conf_paths: "{{ '/etc/php/{{php_version}}' if php_webserver_daemon and php_webserver_daemon != 'apache2' else '/etc/php/{{php_version}}/apache2' }}"
__php_extension_conf_paths: "{{ __php_conf_paths }}/conf.d"
__php_cli_conf_path: "{{__php_conf_paths}}/cli"

__php_apc_conf_filename: 20-apc.ini
__php_opcache_conf_filename: 05-opcache.ini


__php_fpm_daemon: php{{php_version}}-fpm
__php_fpm_conf_path: "/etc/php/{{php_version}}/fpm"
__php_fpm_pool_path: "/etc/php/{{php_version}}/fpm/pool.d"
__php_fpm_pool_conf_path: "{{ __php_fpm_conf_path }}/pool.d/www.conf"
__php_fpm_extension_conf_path: "{{ __php_fpm_conf_path }}/conf.d"

__php_fpm_pool_user: www-data
__php_fpm_pool_group: www-data