---
- name: Copy my.cnf global MySQL configuration.
  template:
    src: my.cnf-Debian.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ overwrite_global_mycnf }}"
  notify: restart mysql
  when: ansible_os_family == 'Debian'

- name: Copy mysql-server.cnf server MySQL configuration.
  template:
    src: mysql-server-RedHat.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ overwrite_global_mycnf }}"
  notify: restart mysql
  when: ansible_os_family == 'RedHat'

- name: Create slow query log file (if configured).
  shell: "touch {{ mysql_slow_query_log_file }} creates={{ mysql_slow_query_log_file }}"
  when: mysql_slow_query_log_enabled

- name: Set ownership on slow query log file (if configured).
  file:
    path: "{{ mysql_slow_query_log_file }}"
    state: file
    owner: mysql
    group: mysql
    mode: 0644
  when: mysql_slow_query_log_enabled

- name: Ensure MySQL is started and enabled on boot.
  service: "name={{ mysql_daemon }} state=started enabled={{ mysql_enabled_on_startup }}"
  register: mysql_service_configuration
