- name: Ensure PHP packages are installed.
  yum:
    name: "{{ php_packages | list }}"
    state: installed  
  notify: restart webserver

- name: Enable software collection executable
  template:
    src: enablephp56scl.sh.j2
    dest: "/etc/profile.d/enablephp56scl.sh"
    owner: root
    group: root
    mode: 0644  
  when: php_use_redhat_softwarecollections

# add script to bashrc for php avaibility during vagrant provisionning
- lineinfile: dest=/etc/bashrc line="source /opt/rh/rh-php56/enable"