- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Make sure sury.org repository can be used
  apt: >
    name=apt-transport-https
    state=present
    update_cache=yes  

- name: Add apt reporitory key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
    keyring: /etc/apt/trusted.gpg.d/php.gpg

- name: Add sury.org repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
    update_cache: yes


- name: Ensure PHP packages are installed.
  apt:
    name: "{{ php_packages | list }}"
    state: present  
  notify: restart webserver