---

- name: Add domains to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.servername }}$'
    line: "127.0.0.1 {{ item.servername }}"
    state: present
  when: apache_vhosts is defined
  with_items: "{{ apache_vhosts }}"