---
- name: Copy Pure-FTPd Fortune File content.
  copy:
    content: "{{ pureftpd_fortune }}"
    dest: "{{ pureftpd_config_fortune_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart Pure-FTPd

- name: Ensure FortunesFile value
  set_fact:
    pureftpd_config_compiled: "{{ pureftpd_config_compiled | combine({ 'FortunesFile': pureftpd_config_fortune_file }) }}"
