---
- name: Create PostgreSQL configuration file.
  template:
    src: postgresql.conf.j2
    dest: "{{ pureftpd_config_db_dir }}/postgresql.conf"
    owner: root
    group: root
    mode: '0600'
  notify: restart Pure-FTPd

- name: Ensure PGSQLConfigFile value
  set_fact:
    pureftpd_config_compiled: "{{ pureftpd_config_compiled | combine({ 'PGSQLConfigFile': pureftpd_config_db_dir + '/postgresql.conf' }) }}"
