---
- name: "User {{ user.name }}: Create system user"
  user:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    home: "{{ user.homedir | default(omit) }}"
    system: no
    createhome: yes
    state: present
