---
- name: Add OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Debian sqlite package
  apt: name={{ sqlite_pkg }} state=present update_cache=yes
  when: ansible_os_family == 'Debian'