---
- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer Debian.
  command: >
    php composer-installer.php
    chdir=/tmp
    creates=/usr/local/bin/composer
  when: ansible_os_family == 'Debian'

- name: Run Composer installer RedHat.
  command: >
    scl enable rh-php56 'php composer-installer.php'
    chdir=/tmp
    creates=/usr/local/bin/composer
  when: ansible_os_family == 'RedHat'

- name: Move Composer into globally-accessible location.
  shell: >
    mv /tmp/composer.phar {{ composer_path }}
    creates={{ composer_path }}

- name: Update Composer to latest version (if configured) Debian.
  shell: >
    scl enable rh-php56 'php {{ composer_path }} self-update'
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_keep_updated and ansible_os_family == 'Debian'

- name: Update Composer to latest version (if configured) RedHat.
  shell: >
    scl enable rh-php56 'php {{ composer_path }} self-update'
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_keep_updated and ansible_os_family == 'RedHat'

- name: Ensure composer directory exists.
  file:
    path: "{{ composer_home_path }}"
    state: directory
    owner: "{{ composer_user }}"
    group: "{{ composer_user }}"

- name: Add GitHub OAuth token for Composer (if configured).
  template:
    src: "auth.json.j2"
    dest: "{{ composer_home_path }}/auth.json"
  when: composer_github_oauth_token != ''

- include: global-require.yml
  when: composer_global_packages|length > 0
