---
mysql_user_home: /root
mysql_root_username: root
mysql_root_password: root

# Set this to `yes` to forcibly update the root password.
mysql_root_password_update: no

mysql_enabled_on_startup: yes

# update my.cnf. each time role is run? yes | no
overwrite_global_mycnf: yes

# Pass in a comma-separated list of repos to use (e.g. "remi,epel"). Used only
# for RedHat systems (and derivatives).
mysql_enablerepo: ""

# Define a custom list of packages to install; if none provided, the default
# package list from vars/[OS-family].yml will be used.
# mysql_packages:
#   - mysql
#   - mysql-server
#   - MySQL-python

# MySQL connection settings.
mysql_port: "3306"
mysql_bind_address: '127.0.0.1'

# Slow query log settings.
mysql_slow_query_log_enabled: no
mysql_slow_query_time: 2

# Memory settings (default values optimized ~512MB RAM).
mysql_max_allowed_packet: "16M"

# Databases.
mysql_databases: []
# Full example:
# mysql_databases:
#   - { name: example, collation: utf8_general_ci, encoding: utf8, replicate: 1 }

# Users
mysql_users: []
# Full Example:
# mysql_users:
#   - { name: example, host: 127.0.0.1, password: secret, priv: *.*:USAGE }

mysql_backup_databases: []

mysql_backup_user: "{{ mysql_root_username}}"
mysql_backup_password: "{{ mysql_root_password}}"

mysql_backup_path: /opt/dumps
mysql_backup_number_of_backups_to_keep: 20

mysql_use_redhat_softwarecollections: true
